service: serverless-bolt-js
frameworkVersion: '2'
provider:
    name: aws
    runtime: nodejs12.x
    environment:
        SLACK_SIGNING_SECRET: ${env:slack_signing_secret}
        SLACK_BOT_TOKEN: ${env:slack_bot_token}
functions:
    slack:
        handler: public/lambda.handler
        events:
            - http:
                  method: post
                  path: slack/events
    ping:
        handler: public/ping.handler
        events:
            - http:
                  path: ping
                  method: post
plugins:
    - serverless-offline
